### ISSUE TITLE
[new rule] guidelines for Avro format

### ISSUE THREAD

**Issue by BirgitBader** [otto-de/api-guidelines#28]
_(i) This issue has been manually transferred from a former internal repository, as a private repository issue cannot be transferred to a public repository._

## Context

Multiple teams expressed the desire to use something other than JSON to encode messages on Kafka. While the Event-Guidelines does not restrict the usage of another format, it also provides no guidance how to properly use another format.

As most of the kafka ecosystem is working with avro, we will focus on the evaluation of guidelines for the avro format.

## Tasks:

- [ ] Check the existing guidelines for JSON if they also apply to the avro format.
- [ ] Check if additional rules make sense
- [ ] Update the guidelines accordingly to include rules for Avro

## Reference

- https://avro.apache.org/
